language: cpp

compiler:
  - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libblas-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_EXAMPLES=ON ..

script: make
