language: cpp

compiler:
  - gcc
  - clang

env:
  - CMAKE_BUILD_TYPE=Release BUILD_SHARED_LIBS=ON

matrix:
  include:
  - compiler: gcc
  - compiler: clang
  - compiler: gcc
    env: CMAKE_BUILD_TYPE=Debug BUILD_SHARED_LIBS=ON
  - compiler: gcc
    env: CMAKE_BUILD_TYPE=Release BUILD_SHARED_LIBS=OFF
  - compiler: gcc
    env: CMAKE_BUILD_TYPE=Debug BUILD_SHARED_LIBS=OFF
  exclude:
  - env: CMAKE_BUILD_TYPE=Release BUILD_SHARED_LIBS=ON

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libblas-dev

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DBUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
  - make VERBOSE=1
